name: Sync
on:
  schedule:
    - cron: '45 23 * * MON-FRI'
    
  workflow_dispatch:
    inputs:
      YEAR: 
        required: false
      MONTH: 
        required: false
      DAY: 
        required: false
  
jobs:
  syncRepo:
    name: "Sync data"
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Run script"
        run: |
          echo "${{ secrets.FILTER }}" | base64 -d > filter
          echo "${{ secrets.CODE }}"   | base64 -d > code
          bash code
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
          Y: ${{ github.event.inputs.YEAR }}
          M: ${{ github.event.inputs.MONTH }}
          D: ${{ github.event.inputs.DAY }}
         
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ secrets.NAME }}
          author_email: ${{ secrets.MAIL }}
          message: 'GH Action'
