name: Sync
on:
  schedule:
    - cron: '45 23 * * *'
    
  workflow_dispatch:
  
jobs:
  syncRepo:
    name: syncRepo
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Pushes sync file
        run: |
          echo "${{ secrets.FILTER }}" | base64 -d >> /tmp/filter
          echo "${{ secrets.CODE }}"   | base64 -d >> /tmp/code
          ADIR=$(pwd)
          bash /tmp/code
          cd $ADIR
          git config --global user.name "${{ secrets.NAME }}"
          git config --global user.email "${{ secrets.MAIL }}"
          git add .
          git commit -m "Update data to $(date +'%Y-%m-%d')"
          git push
