name: Sync
on:
  schedule:
    - cron: '45 23 * * MON-FRI'
    
  workflow_dispatch:
  
jobs:
  syncRepo:
    name: "Sync data"
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Run script"
        run: |
          echo "${{ secrets.FILTER }}" | base64 -d >> /tmp/filter
          echo "${{ secrets.CODE }}"   | base64 -d >> /tmp/code
          bash /tmp/code
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

      - name: Debug
        run: 
          echo date > $(date -u +"%Y-%m-%dT%H:%M:%SZ").txt
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'Charles Santos'
          author_email: 'thyarles@gmail.com'
          message: 'GH Action'
