name: Sync
on:
  schedule:
    - cron: '45 23 * * *'
    
  workflow_dispatch:
  
jobs:
  syncRepo:
    name: "Sync data"
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - name: "Run script"
        run: |
          echo "${{ secrets.FILTER }}" | base64 -d >> /tmp/filter
          echo "${{ secrets.CODE }}"   | base64 -d >> /tmp/code
          bash /tmp/code
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Charles Santos
          author_email: thyarles@gmail.com
          message: GH Action
